require:
  - rubocop-performance
  - rubocop-rails

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Include:
    - 'app/views/api/**/*.rabl'
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

# Don't prefer is_a? over kind_of?
Style/ClassCheck:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

# Both double and single quotes are OK
Style/StringLiterals:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Rails/Date:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

#Style/TrailingCommaInArguments:
#Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/WordArray:
  Enabled: false


Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

# a == 0 is not the same as a.zero?, when a is not a number
Style/NumericPredicate:
  Enabled: false

Style/FormatString:
  Enabled: false

# update_attribute makes sense in some cases
Rails/SkipsModelValidations:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Naming/FileName:
  Exclude:
       - 'Gemfile'
       - 'db/**/*'

Rails/ReversibleMigration:
  Exclude:
       - 'db/migrate/20150111085317_polymorph_asset.rb'

Layout/DotPosition:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Performance/InefficientHashSearch:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Minitest/AssertEmpty:
  Enabled: false

Minitest/AssertIncludes:
  Enabled: false

Minitest/AssertMatch:
  Enabled: false

Minitest/RefuteEmpty:
  Enabled: false

Minitest/RefuteFalse:
  Enabled: false

Minitest/RefuteIncludes:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false
