export const POLICIES_REQUEST = 'POLICIES_REQUEST';
export const POLICIES_SUCCESS = 'POLICIES_SUCCESS';
export const POLICIES_FAILURE = 'POLICIES_FAILURE';

export const SCAP_CONTENT_PROFILES_REQUEST = 'SCAP_CONTENT_PROFILES_REQUEST';
export const SCAP_CONTENT_PROFILES_SUCCESS = 'SCAP_CONTENT_PROFILES_SUCCESS';
export const SCAP_CONTENT_PROFILES_FAILURE = 'SCAP_CONTENT_PROFILES_FAILURE';
