query($id: String!) {
  ovalPolicy(id: $id) {
    id
    name
    period
    cronLine
    weekday
    dayOfMonth
    description
    ovalContent {
      id
      name
      url
      originalFilename
      changedAt
    }
    hostgroups {
      nodes {
        id
        descendants {
          nodes {
            id
          }
        }
      }
    }
  }
}
