name: Ruby Testing
on:
  pull_request:
  push:
    branches:
    - master
env:
  BUNDLE_WITHOUT: journald:development:console:libvirt
  RAILS_ENV: test
  DATABASE_URL: postgresql://postgres:@localhost/test
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
jobs:
  # rubocop:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.6
  #         bundler-cache: true
  #     - name: Run rubocop
  #       run: bundle exec rubocop
  test_ruby:
    runs-on: ubuntu-latest
    # needs: rubocop
    services:
      postgres:
        image: postgres:12.1
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        foreman-core-branch: [develop]
        foreman-rex-branch: [master]
        ruby-version: [2.5, 2.6]
    steps:
      - name: Install build packages
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libcurl4-openssl-dev zlib1g-dev libpq-dev
      - uses: actions/checkout@v2
        with:
          repository: theforeman/foreman
          ref: ${{ matrix.foreman-core-branch }}
      - uses: actions/checkout@v2
        with:
          repository: theforeman/foreman_remote_execution
          ref: ${{ matrix.foreman-rex-branch }}
          path: foreman_remote_execution
      - uses: actions/checkout@v2
        with:
          path: foreman_openscap
      - name: Setup Bundler
        run: |
          echo "gem 'foreman_openscap', path: './foreman_openscap'" > bundler.d/foreman_openscap.local.rb
          echo "gem 'foreman_remote_execution', path: './foreman_remote_execution'" > bundler.d/foreman_remote_execution.local.rb
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Prepare test env
        if: github.event_name != 'push'
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake db:test:prepare
      - name: Run plugin tests
        if: github.event_name != 'push'
        run: |
          bundle exec rake test:foreman_openscap
          bundle exec rake test
